### ISSUE TITLE
garbled characters

### ISSUE THREAD

**Issue by R0FGV** [Shuzhengz/TPFanCtrl2#3]
Hello, the Chinese system I am using has garbled characters, and the temperature sign has changed to: 癈
![image](https://user-images.githubusercontent.com/19688305/131518196-3f4ca448-ba72-4310-a0ce-3865b4e00cca.png)

**Comment by Shuzhengz** [comment]
huh that's weird

**Comment by Shuzhengz** [comment]
try #4 and see if it works

**Comment by Shuzhengz** [comment]
> > try #4 and see if it works
> 
>     When to recompile the file? 
> 
> 

try testing it in visual studio first

**Comment by R0FGV** [comment]
> > > try #4 and see if it works
> > 
> > 
> > ```
> > When to recompile the file? 
> > ```
> 
> try testing it in visual studio first

yep~ test completion🙂

**Comment by Shuzhengz** [comment]
@R0FGV see 2.0.2 release
