### ISSUE TITLE
Thinkpad X1 Carbon Gen 9 - wrong sensor

### ISSUE THREAD

**Issue by knutov** [Shuzhengz/TPFanCtrl2#33]
It seems wrong sensor is used to mesure CPU temperature with X1 carbon gen 9:

![изображение](https://user-images.githubusercontent.com/255869/165048531-8bfcc8e4-2088-4dd4-9d81-74c6c04619a2.png)

So in "smart mode" with settings like
```
Level=44 0 
Level=45 1 
Level=46 2 
Level=48 5 
Level=50 7 
```
it's always run at speed 7 while real cpu temperature is 42.

X1 carbon gen 9 with I7 - 20XW005TRT
Latest BIOS - N32ET75W 1.51
Latest Windows 10 Pro
Latest TPFanCtrl2

How to fix it?

**Comment by Shuzhengz** [comment]
Yeah I just got a new computer and the program stopped working. I think newer ThinkPads have different EC addresses or just a different way to control the fan with their new intelligent cooling that you can't turn off. I'll be working on a fix for this once I get a chance to.
Thank you for reporting the issue!

**Comment by knutov** [comment]
fan control work fine, in manual mode I can set any speed (in fact with i7 I have to always use speed 7 to prevent it to be too hot to work with keyboard in "optimized" and "performance" mode)

**Comment by Shuzhengz** [comment]
yeah it seems like lenovo has moved the address for the temperature sensor in the EC

**Comment by jtlarson** [comment]
My workaround is to modify the ini file to ignore the pwr and pci sensors:

IgnoreSensors=no5,pci,pwr

**Comment by knutov** [comment]
> IgnoreSensors=no5,pci,pwr

Thanks, it works!
