### ISSUE TITLE
garbled characters V.2.1.4

### ISSUE THREAD

**Issue by Ew687** [Shuzhengz/TPFanCtrl2#38]
Hello - sorry my english
V.2.1.4 encoding problem

https://ibb.co/Rg2PqRp
<a href="https://ibb.co/Rg2PqRp"><img src="https://i.ibb.co/Rg2PqRp/e.png" alt="e" border="0"></a>

**Comment by Shuzhengz** [comment]
Hi
I'm not really sure what the problem is, it would be great if you can explain the problem a little
Thank you!

**Comment by Ew687** [comment]
Hi

Display issues on systems with garbled characters
With temperatures, I have bushes everywhere

V2.1.3 

1 cpu 37° C (0x78)
3 crd 35° C (0x7a)
5 no5 35° C (0x7c)
6 x7d 31° C (0x7d)
7 bat 35° C (0x7e)



V2.1.4

1 cpu 37Â° C (0x78)
3 crd 35Â° C (0x7a)
5 no5 35Â° C (0x7c)
6 x7d 31Â° C (0x7d)
7 bat 35Â° C (0x7e)


Regards

**Comment by Shuzhengz** [comment]
oooh okay I will fix it in a bit
thank you!

**Comment by Shuzhengz** [comment]
okay can you try this build? it should fix it

[tpfc.zip](https://github.com/Shuzhengz/TPFanCtrl2/files/9099456/tpfc.zip)

**Comment by Ew687** [comment]
Thank you - it's okay now
Was that a mistake you overlooked?

greetings

**Comment by Shuzhengz** [comment]
Visual studio didn't include the encoding formats when upgrading the project to be compatible with the new visual studio version, so I just added it back in.

Thank you!

**Comment by Ew687** [comment]
Thank you :)

**Comment by Shuzhengz** [comment]
yeah ofc :)
