### ISSUE TITLE
messy code in chinese characters on temprature displayed

### ISSUE THREAD

**Issue by idolumsky** [Shuzhengz/TPFanCtrl2#42]
messy code in chinese characters on temprature displayed 
52掳 C
in right way is 52°C

**Comment by Shuzhengz** [comment]
Hi, can you try this build [here](https://github.com/Shuzhengz/TPFanCtrl2/files/9099456/tpfc.zip) and see if it fixes it?
Thank you!

**Comment by Shuzhengz** [comment]
fixed in 2.1.5
