### ISSUE TITLE
The display of Celsius in Chinese is abnormal

### ISSUE THREAD

**Issue by R0FGV** [Shuzhengz/TPFanCtrl2#48]
![image](https://user-images.githubusercontent.com/19688305/193518961-e241eae4-3c91-40aa-a38b-ea2d426ee35e.png)

**Comment by Shuzhengz** [comment]
Thank you for reporting this

Can you check the current local language for non-unicode programs under `control panel > clock and region > region > administrative tab > change system local`?

Thanks

**Comment by R0FGV** [comment]
Version 2.1.5 solves this problem perfectly

**Comment by Shuzhengz** [comment]
oh nice
