### ISSUE TITLE
exe file to download

### ISSUE THREAD

**Issue by recycletechno** [Shuzhengz/TPFanCtrl2#56]
Hello!

I'm suffering from high fan speed at low (45-50 C) temperatures on my Lenovo Carbon X1 Gen 10 when charging. I would like to make my fan start at higher temps. I have found your repo with source code and do not know how to make it work on my PC. I have found only original exe on this link (https://sourceforge.net/projects/tp4xfancontrol/). Somehow it made my laptop loose its battery and I hardly recovered it :) And it was not the case of two fans laptops as I have. It was updated as far as 2015.

Do you have any place where one can find .exe files from source or any "short-way" to make .exe file by myself

Thank you!

**Comment by Shuzhengz** [comment]
Hi, here's the link to the release page: https://github.com/Shuzhengz/TPFanCtrl2/releases

The `.exe` executable and the `.ini` initializer file are both inside the compressed `.zip` file

Make sure to also have [TVicPort](https://www.entechtaiwan.com/dev/port/index.shtm) installed for the program to work
