### ISSUE TITLE
cant install tvicport.dll from website

### ISSUE THREAD

**Issue by soapheadd** [Shuzhengz/TPFanCtrl2#57]
The download button doesnt work

**Comment by Shuzhengz** [comment]
Here's the downloaded zip file 
[tvicport.zip](https://github.com/Shuzhengz/TPFanCtrl2/files/12320626/tvicport.zip)

**Comment by soapheadd** [comment]
i installed the program, but i dont know where the dll is still

**Comment by Shuzhengz** [comment]
oh you can't find the dll as it is made propirtary by the devs, the program should pick up tvicport automatically though
