### ISSUE TITLE
Where is exe file?

### ISSUE THREAD

**Issue by feather7** [Shuzhengz/TPFanCtrl2#58]
I cant find exe file.

**Comment by Shuzhengz** [comment]
On the [release page](https://github.com/Shuzhengz/TPFanCtrl2/releases/tag/2.1.5), if you click on the **_TPFC2_2.1.5.zip_** link, it will download the `.zip` file that includes both `fancontrol.exe` executable and `TPFanControl.ini` config file, make sure to have both of them in the same directory in order for it to run properly.

Also, make sure to have `tvicport` installed in order for the program to function, you can find it [here](https://www.entechtaiwan.com/dev/port/index.shtm)
