### ISSUE TITLE
tvicport.sys missing in app folder or failed to load

### ISSUE THREAD

**Issue by zengzuo613** [Shuzhengz/TPFanCtrl2#66]
## description

When I run fancontrol. exe, the error is as follows:

![image](https://github.com/Shuzhengz/TPFanCtrl2/assets/76633368/78205637-bccd-45d0-be0d-60d2bf827d33)

I had install tvicport

**Comment by Shuzhengz** [comment]
Hi, can you try uninstalling tvicport and installing the old version of TPFC ([v0.62](https://thinkwiki.de/tpfancontrol/tpfc_v062.zip)), and then try again?

**Comment by zengzuo613** [comment]
Thank you, I have reinstalled tvicport and resolved it

**Comment by zengzuo613** [comment]
[如何降低 ThinkPad T14 Gen 4 风扇噪音](https://my.oschina.net/fanwen996/blog/11205682)

**Comment by hung123-alt** [comment]
I can't use version 2.3.3, the app keeps crashing, can anyone help me control the download with ultraview?
