### ISSUE TITLE
Lenovo P50 Blacksreen

### ISSUE THREAD

**Issue by Enderman117** [Shuzhengz/TPFanCtrl2#67]
Hi, I have a Lenovo P50 Type 20EQ. With Specs i7-6820HQ, 32GB DDR4 2133mhz, Quadro M1000M Graphics, W/ Intel HD Graphics 530. I also have the latest BIOS update installed. So If I run TPFANCTRL, with discrete GPU only, the laptop goes to a black screen ( I am running Windows 11 Pro) If I try Remotedesktop, as the laptop is still on with the blackscreen, a few seconds pass by, on remote desktop seem's its loading something, and says the display componets failed to start. With Hybrid graphics, I get a BSOD Saying something like VIDEO_MEMORY_MANAGEMENT_THERMAL. How do I fix this?

**Comment by BavariumExecutor** [comment]
the original version does that, use V2.1.5 B(As stated in the readme)
https://github.com/Shuzhengz/TPFanCtrl2/releases/tag/2.1.5_B

**Comment by Shuzhengz** [comment]
Hi, you can refer to issue #23 for this, but in short we don't have a complete fix yet, best solution we have right now is with pre-release [v2.1.5B](https://github.com/Shuzhengz/TPFanCtrl2/releases/tag/2.1.5_B) where the temperature seems to still be broken, so only use it in manual mode with fan speed set high so it doesn't damage the device.

**Comment by Enderman117** [comment]
Hello so the issue is that, I set the fan speed to the max speed 7, in manual mode. The tool keeps on switching to Smart (TPFANCONTROL.INI) So I cant use manual mode. Any fixes?

**Comment by Shuzhengz** [comment]
Hi, the program switches to smart mode if the temperature is too high as a protective measurement, you can increase the `ManModeExit` value in `TPFanControl.ini` to modify this behaviour.
